name: simple_chat_application
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  shimmer: ^1.1.0
  flutter_slidable: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/person1.jpg
    - assets/images/person2.png
    - assets/images/person3.jpg
    - assets/images/person4.png
    - assets/images/person5.jpg
    - assets/images/person6.jpg
    - assets/images/person7.jpg
    - assets/images/chat-background-1.jpg